package:
  name: biowrappers-museq
  version: "0.1.1"
  
source:
  hg_url: ssh://hg@bitbucket.org/aroth85/museq
  hg_tag: 0.1.1
  
requirements:
  build:
    - cython
    - python

    - numpy
    - pandas
    - pysam >=0.8.4
    - biowrappers-pyvcf
    - pytables
    - pyyaml
    - scikit-learn ==0.17
    - scipy        
    - setuptools
    
  run:
    - python
    
    - numpy
    - pandas
    - pysam >=0.8.4
    - biowrappers-pyvcf
    - pytables
    - pyyaml    
    - scikit-learn ==0.17
    - scipy
    

build:
  number: 0
    
about:
  home: https://bitbucket.org/aroth85/museq
  license:  GPLv3
  license_file: LICENSE.txt