package:
  name: biowrappers-distribution
  version: "0.1.0"

requirements:
  run:
    - bcftools
    - biobambam
    - biowrappers
    - bwa
    - bx-python
    - htslib
    - nuseq
    - pandas
    - pypeliner
    - pysam
    - pysftp
    - pytables
    - pyvcf
    - sambamba
    - samtools
    - snpeff
    - strelka
    - vardict
    - vardict-java

build:
  number: 0
