package:
  name: biowrappers-pyvcf
  version: '0.6.7'

source:
  fn: PyVCF-0.6.7.tar.gz
  url: https://pypi.python.org/packages/source/P/PyVCF/PyVCF-0.6.7.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - vcf.test
    - vcf

about:
  home: https://github.com/jamescasbon/PyVCF
  license: BSD
  summary: A Variant Call Format reader for Python
