package:
  name: biowrappers-stack
  version: "0.1.0"

requirements:
  build:
    - biowrappers-museq ==0.1.0
    - biowrappers-mutect ==1.1.7
    - biowrappers-snpeff ==4.1l_GRCh37.75
    - biowrappers-strelka ==1.0.14
    - biowrappers-vardict ==1.4.3
  
  run:
    - biowrappers-museq ==0.1.0
    - biowrappers-mutect ==1.1.7
    - biowrappers-snpeff ==4.1l_GRCh37.75
    - biowrappers-strelka ==1.0.14
    - biowrappers-vardict ==1.4.3

build:
  number: 1
