# Replace {ref_db_path} with the path were data is stored.
# Note the example pipeline replaces this automatically using the command line argument --ref_db_path.
#
# If the sections for mutect, nuseq, strelka or vardict are excluded, those tools will not be run. 
#
# For each section (except snpeff) only the local_path entry is required for the pipeline.
# For snpeff the db entry is required.
# The remaining information is there to allow the config to be used with the init_db_pipeline.
databases:
  cosmic:
    download_method: sftp
    user_name: cosmic_user_name
    password: cosmic_password
    host: sftp-cancer.sanger.ac.uk
    remote_paths:
      coding: /files/grch37/cosmic/v75/VCF/CosmicCodingMuts.vcf.gz 
      non_coding: /files/grch37/cosmic/v75/VCF/CosmicNonCodingVariants.vcf.gz
    local_path: '{ref_db_path}/cosmic_v75.vcf.gz'
  
  dbsnp:
    url: ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b146_GRCh37p13/VCF/common_all_20151104.vcf.gz
    local_path: '{ref_db_path}/dbsnp_b146_GRCh37p13.vcf.gz'
  
  mappability:
    url: http://hgdownload-test.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeMapability/release3/wgEncodeCrgMapabilityAlign50mer.bigWig
    local_path: '{ref_db_path}/wgEncodeCrgMapabilityAlign50mer.bigWig'
  
  ref_genome: 
    url: http://www.bcgsc.ca/downloads/genomes/9606/hg19/1000genomes/bwa_ind/genome/GRCh37-lite.fa
    local_path: '{ref_db_path}/GRCh37-lite.fa'
  
  snpeff:
    db: GRCh37.75
  
cosmic_status:
  kwargs:
    split_size: 10000
    
dbsnp_status:
  kwargs:
    split_size: 10000
        
mappability:
  kwargs:
    split_size: 10000

mutect:
  kwargs:
    split_size: 1000000 

nuseq:
  kwargs:
    indel_threshold: 0.05
    min_normal_depth: 1
    min_tumour_depth: 1
    min_somatic_probability: 0.75

nuseq_multi_sample:
  kwargs:
    indel_threshold: 0.05
    min_normal_depth: 1
    min_tumour_depth: 1
    min_somatic_probability: 0.75

snpeff:
  kwargs:
    split_size: 1000

snv_counts:
  kwargs:
    count_duplicates: False
    min_bqual: 30
    min_mqual: 30
    split_size: 10000

strelka:
  kwargs:
    split_size: 1000000
    # True if WGSS / False if exome
    use_depth_thresholds: True

tri_nucleotide_context:
  kwargs:
    split_size: 10000

vardict:
  kwargs:
    split_size: 1000000
    min_allele_frequency: 0.01
