about:
  home: 'http://snpeff.sourceforge.net/'
  license: 'LGPLv3'
  summary: 'Genetic variant annotation and effect prediction toolbox'

package:
  name: biowrappers-snpeff
  version: '4.1l_GRCh37.75'

build:
  number: 0

source:
  fn: snpEff_v4_1l_core.zip
  md5: 43dd4b41f3223bbb4cc094ec5c5e2aac
  url: http://downloads.sourceforge.net/project/snpeff/snpEff_v4_1l_core.zip

requirements:
  build:
    - java-jdk
  
  run:
    - java-jdk

test:
  commands:
    - bw-snpeff -version
