package:
  name: biowrappers-mutect
  version: "1.1.7"

source:
  path: src

requirements:
  run:
    - python >=2.7,<3

build:
  binary_relocation: False
  number: 1
  
about:
  home: https://github.com/broadinstitute/mutect
  license_file: LICENSE
